[project]
name = "notte-agent"
version = "1.4.4.dev"
description = "Notte Web AI Agents"
readme = "README.md"
authors = [
    { name = "Notte Team ", email = "hello@notte.cc" }
]
packages = [
  { include = "notte_agent", from = "src" },
]

requires-python = ">=3.11"
dependencies = [
    "notte_core==1.4.4.dev",
    "notte_browser==1.4.4.dev",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
