[project]
name = "notte-integrations"
version = "1.4.4.dev"
description = "The integrations for Notte"
readme = "README.md"
authors = [
    { name = "Notte Team ", email = "hello@notte.cc" }
]
packages = [
    { include = "notte_integrations", from = "src" },
]


requires-python = ">=3.11"
dependencies = [
    "notte_core==1.4.4.dev",
    "notte_browser==1.4.4.dev",
    "notte_agent==1.4.4.dev",
    "discord-py>=2.3.0,<2.5.0",
    "fastapi>=0.115.8",
    "uvicorn>=0.29.0",
    "hvac>=2.3.0",
    "browserbase>=1.2.0",
    "browser-use>=0.1.40",
    "langchain-google-genai>=2.1.1",
    "slack-sdk>=3.34.0",
]



[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
