[project]
name = "notte-sdk"
version = "1.4.4.dev"
description = "The SDK for Notte"
readme = "README.md"
authors = [
    { name = "Notte Team ", email = "hello@notte.cc" }
]
packages = [
  { include = "notte_sdk", from = "src" },
]

requires-python = ">=3.11"
dependencies = [
    "halo>=0.0.31",
    "notte-core==1.4.4.dev",
    "websockets>=13.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
